/// Original lines and gentle prompts written for Tide. One is shown per day
/// when there is no past reflection to resurface.
const dailyLines = <String>[
  'Small steps still count.',
  'What would make today feel lighter?',
  "You're allowed to go slowly.",
  'Notice one thing that went right.',
  'Rest is part of the plan.',
  'What can wait until tomorrow?',
  'Drink some water. Look out of a window.',
  "Be as patient with yourself as you'd be with a friend.",
  'One thing at a time is plenty.',
  'What are you looking forward to this week?',
  'A rough first try beats a perfect idea on hold.',
  'Who would you like to hear from today?',
  'A short walk can change a whole afternoon.',
  'What did you do well yesterday?',
  "It's fine to leave some things unfinished.",
  'Choose one thing to do with care.',
  'Breathe out a little longer than you breathe in.',
  "What's taking up space in your head? Capture it.",
  'Good days are often made of ordinary things.',
  'What would future you thank you for?',
  "You don't need to earn a break.",
  'Say no to one thing, kindly.',
  'What made you smile recently?',
  'Let the easy task be easy.',
  'Tidy one small corner.',
  'How are you, really?',
  'Progress hides in the quiet days too.',
  'What small kindness could you offer someone?',
  'Put the phone down for ten minutes.',
  'What would a calm version of today look like?',
  'Your pace is your pace.',
  'Leave a little room for surprise.',
  "What's one thing you're grateful for right now?",
  'Stretch. Your shoulders will thank you.',
  'Start with the part you understand.',
  'What are you carrying that you could set down?',
  'A plan is a guide, not a promise.',
  'Make something, however small.',
  'What did you learn this week?',
  'Eat something good, slowly.',
  "It's okay to ask for help.",
  'Which task would make the rest easier?',
  'Enough is a good amount.',
  'Step outside, even briefly.',
  'What does your body need today?',
  'Finish one thing before starting the next.',
  "Today doesn't have to be impressive.",
  "What's one thing you'd like to remember about today?",
  'Keep it simple. Then keep it going.',
  "Send the message you've been meaning to send.",
  'Some seasons are for sowing, not harvesting.',
  'What would you do if it only had to be good enough?',
  'Find one quiet minute and keep it.',
  'Let yesterday stay in yesterday.',
  "What's the next small step?",
  'Celebrate something tiny.',
  "You're further along than you think.",
  'Put on a song you love.',
  'What could you make easier for tomorrow?',
  'Go gently.',
];
